---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :
# tasks file for ip.rootcert

- include_vars: debian.yml
  when: ansible_os_family == 'Debian' or 
        ansible_os_family == 'Kali GNU/Linux'

- include: linux.yml
  when: ansible_os_family == 'Debian' or 
        ansible_os_family == 'RedHat' or
        ansible_os_family == 'Kali GNU/Linux'

- include: freebsd.yml
  when: ansible_os_family == 'FreeBSD'
  with_items: '{{ rootcerts }}'

