---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :

- name: Install shorewall
  package:
    name: shorewall
    state: present

# Firewall zones

- name: Configure shorewall zones
  template:
    src: templates/shorewall/zones.j2
    dest: /etc/shorewall/zones
  register: zones
  vars:
    shorewall_zones: '{{ firewall_zones | default(firewall_zones_default) }}'

# Firewall policies

- name: Configure shorewall policies
  template:
    src: templates/shorewall/policy.j2
    dest: /etc/shorewall/policy
  register: policies
  vars:
    shorewall_policies: '{{ firewall_policies | default(firewall_policies_default) }}'

# Firewall interfaces

- name: Configure shorewall interfaces
  template:
    src: templates/shorewall/interfaces.j2
    dest: /etc/shorewall/interfaces
  register: interfaces
  vars:
    shorewall_interfaces: '{{ firewall_interfaces }}'

# Firewall SNAT

- name: Configure shorewall SNAT
  template:
    src: templates/shorewall/snat.j2
    dest: /etc/shorewall/snat
  register: snat
  when: shorewall_snat_host is defined or shorewall_snat_group is defined

# Firewall Rules

- name: Configure shorewall rules
  template:
    src: templates/shorewall/rules.j2
    dest: /etc/shorewall/rules
  register: rules
  vars:
    shorewall_rules: '{{ firewall_rules | default(firewall_rules_default) }}'

# Firewall Routing

- name: Configure shorewall providers
  template:
    src: templates/shorewall/providers.j2
    dest: /etc/shorewall/providers
  register: providers
  vars:
    shorewall_rules: '{{ firewall_routerules }}'
  when: firewall_providers is defined

- name: Configure shorewall routing rules
  template:
    src: templates/shorewall/rtrules.j2
    dest: /etc/shorewall/rtrules
  register: rtrules
  vars:
    shorewall_rules: '{{ firewall_providers }}'
  when: firewall_routerules is defined and firewall_providers is defined

# Service

- name: Enable shorewall startup
  lineinfile:
    path: /etc/default/shorewall
    regexp: '^startup='
    line: 'startup=1'
  register: startme

- name: Restart shorewall
  service:
    name: shorewall
    state: restarted
  when: zones.changed or interfaces.changed or policies.changed or rules.changed or startme.changed or snat.changed or (rtrules is defined and rtrules.changed) or (providers is defined and providers.changed)

