---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :

- name: Create temporary CA directory
  tempfile:
    state: directory
    suffix: ovpn
  register: ca_tmp
  delegate_to: localhost
  changed_when: false

- name: Decrypt CA private files to {{ ca_tmp.path }}
  copy:
    content: "{{ item.value }}\n"
    dest: '{{ ca_tmp.path }}/{{ item.key }}'
  delegate_to: localhost
  with_dict: '{{ openvpn_ca_files }}'
  no_log: true
  changed_when: false

- include_tasks: client-windows.yml
  when:
    - openvpn_role is defined
    - openvpn_role == 'client'
    - ansible_os_family == 'Windows'

- name: Cleanup extracted temporary keys from {{ ca_tmp.path }}
  file:
    path: '{{ item }}'
    state: absent
  delegate_to: localhost
  with_items:
    - '{{ ca_tmp.path }}/{{ openvpn_filename_key_ca }}'
    - '{{ ca_tmp.path }}/{{ openvpn_filename_cert_ca }}'
    - '{{ ca_tmp.path }}/{{ openvpn_filename_csr }}'
    - '{{ ca_tmp.path }}/{{ openvpn_filename_key }}'
    - '{{ ca_tmp.path }}/{{ openvpn_filename_cert }}'
    - '{{ ca_tmp.path }}/{{ openvpn_filename_ta }}'
    - '{{ ca_tmp.path }}'
  changed_when: false

