---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :

- include_tasks: client-windows.yml
  when:
    - openvpn_role is defined
    - openvpn_role == 'client'
    - ansible_os_family == 'Windows'

- name: Upload OpenVPN certificates to server
  synchronize:
    src: '{{ openvpn_store_path }}/'
    dest: '{{ openvpn_server_keys_dir }}/'
    rsync_opts:
      - '--include=*.crt'
      - '--exclude=*'
  when:
    - openvpn_role is defined
    - openvpn_role == 'server'

