---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :

- name: Create OpenVPN static files
  template:
    src: 'templates/static.j2'
    dest: '{{ openvpn_server_static_path }}/{{ static.key }}'
  with_dict: '{{ openvpn_static }}'
  loop_control:
    loop_var: static

