---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :

- name: Fetch SSL certificate inventory (FreeNAS)
  uri:
    url: '{{ getcert_freenas_api_url }}/api/v1.0/system/certificate'
    method: GET
    user: '{{ getcert_freenas_api_user }}'
    password: '{{ getcert_freenas_api_password }}'
    body_format: json
    force_basic_auth: yes
    validate_certs: False
  delegate_to: localhost
  register: ssl_inventory
  no_log: true

- name: Upload existing SSL certificate (FreeNAS)
  copy:
    dest: '{{ cert_path }}'
    content: >
      {{ item.cert_certificate }}{{ getcert_freenas_ca }}
  when: common_name == item.cert_common
  with_items:
  - '{{ ssl_inventory.json }}'

- name: Upload existing SSL private key (FreeNAS)
  copy:
    dest: '{{ privkey_path }}'
    content: >
      {{ item.cert_privatekey }}
  when:  common_name == item.cert_common
  with_items:
  - '{{ ssl_inventory.json }}'

