---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :

- include_tasks: 'unix-ssl-all.yml'

- name: Generate SSL private key (MSAD)
  openssl_privatekey:
    path: '{{ privkey_path }}'
    size: 4096
    state: present
    type: RSA
    owner: '{{ getcert_ssl_owner }}'
    group: '{{ getcert_ssl_group }}'
  register: msad_privkey
  when: not ssl_key_remote.stat.exists

- name: Generate SSL signing request (MSAD)
  openssl_csr:
    path: '{{ csr_path }}'
    privatekey_path: '{{ privkey_path }}'
    common_name: '{{ common_name }}'
    organization_name: '{{ getcert_csr_org }}'
    locality_name: '{{ getcert_csr_locale }}'
    state_or_province_name: '{{ getcert_csr_state }}'
    country_name: '{{ getcert_csr_country }}'
    email_address: '{{ getcert_csr_contact }}'
    digest: sha256
    owner: '{{ getcert_ssl_owner }}'
    group: '{{ getcert_ssl_group }}'
    subject_alt_name:
      - 'DNS:{{ common_name }}'
  register: msad_csr
  when: not ssl_crt_remote.stat.exists or ssl_valid_remote.failed

- name: Submit certificate signing request (MSAD)
  uri:
    url: 'https://{{ getcert_msad_server }}/certsrv/certfnsh.asp'
    user: '{{ getcert_msad_user }}'
    password: '{{ getcert_msad_password }}'
    force_basic_auth: yes
    headers: '{{ getcert_msad_ssl_headers }}'
    body: "Mode=newreq&CertRequest={{ lookup('file', msad_csr.filename) | regex_replace('\\r|\\n', '') | regex_replace( '\\+', '%2B' ) | regex_replace( ' ', '+' ) }}&CertAttrib=CertificateTemplate:{{ getcert_msad_template }}%0D%0A&TargetStoreFlags=0&SaveCert=yes&ThumbPrint="
    return_content: yes
  register: msad_certrqxt
  when: msad_csr.changed or not ssl_crt_remote.stat.exists

- name: Download issued certificate (MSAD)
  uri:
    url: "https://{{ getcert_msad_server }}/certsrv/{{ msad_certrqxt.content | regex_search('(certnew\\.cer\\?ReqID=[0-9]*)&') }}"
    user: '{{ getcert_msad_user }}'
    password: '{{ getcert_msad_password }}'
    force_basic_auth: yes
    headers: '{{ getcert_msad_ssl_headers }}'
    dest: '{{ cert_path }}'
  when: msad_csr.changed or not ssl_crt_remote.stat.exists

