---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :

- name: Install certbot ACME client
  package:
    name: certbot
    state: present

- name: Create ACME group
  group:
    name: '{{ getcert_le_user.group }}'
    gid: '{{ getcert_le_user.gid }}'
    state: present

- name: Create ACME user
  user:
    name: '{{ getcert_le_user.name }}'
    shell: '{{ getcert_le_user.shell }}'
    uid: '{{ getcert_le_user.uid }}'
    group: '{{ getcert_le_user.group }}'
    home: '{{ getcert_le_user.home }}'
    createhome: yes
    groups: '{{ getcert_le_user.groups }}'

- name: Create ACME directories
  file:
    path: '{{ item.value }}'
    state: directory
    owner: '{{ getcert_le_user.name }}'
    group: '{{ getcert_le_user.group }}'
  with_dict: '{{ getcert_le_dirs }}'

- name: Verify ACME working directory permissions
  #command: 'chown -R {{ getcert_le_user.name }}:{{ getcert_le_user.group }} {{ getcert_le_dirs.work }}'
  file:
    path: '{{ getcert_le_dirs.work }}'
    owner: '{{ getcert_le_user.name }}'
    group: '{{ getcert_le_user.group }}'
    recurse: yes

- name: Create ACME site directories
  file:
    path: '{{ item.document_root }}/.well-known'
    state: directory
    owner: '{{ getcert_le_user.name }}'
    group: '{{ getcert_le_user.group }}'
    mode: 0775
  when:
    - item.ssl is defined
    - item.ssl == 'acme'
  with_items: '{{ getcert_sites }}'

- name: Generate SSL certificate (ACME)
  command: 'certbot certonly --agree-tos -m {{ item.item.item.le_mail | default(getcert_le_mail) }} --config-dir {{ getcert_le_dirs.config }} --logs-dir {{ getcert_le_dirs.logs }} --work-dir {{ getcert_le_dirs.work }} --webroot -w {{ item.item.item.document_root }} -d {{ item.item.item.server_name }}'
  when:
    - not item.item.item.enabled is defined or item.item.item.enabled == True
    - item.item.item.ssl is defined
    - item.item.item.ssl == 'acme'
    - not item.item.stat.exists
    - not item.failed
  become: yes
  become_user: '{{ getcert_le_user.name }}'
  with_items: '{{ ssl_valid_remote.results }}'

- name: Renew SSL certificate (ACME)
  command: 'certbot renew --agree-tos -m {{ item.item.item.le_mail | default(getcert_le_mail) }} --config-dir {{ getcert_le_dirs.config }} --logs-dir {{ getcert_le_dirs.logs }} --work-dir {{ getcert_le_dirs.work }} --webroot -w {{ item.item.item.document_root }} -d {{ item.item.item.server_name }}'
  when:
    - not item.item.item.enabled is defined or item.item.item.enabled == True
    - item.item.item.ssl is defined
    - item.item.item.ssl == 'acme'
    - item.item.stat.exists
    - item.failed
  become: yes
  become_user: '{{ getcert_le_user.name }}'
  with_items: '{{ ssl_valid_remote.results }}'

#- name: Upload certbot config (ACME)
#  template:
#    src: 'templates/acme-renewal.conf.j2'
#    dest: '{{ getcert_certbot_config_dir }}/renewal/{{ item.server_name }}.conf'
#    owner: 'root'
#    group: 'root'
#    mode: '0644'
#  when:
#    - (item.item.item.enabled is defined and item.item.item.enabled) or
#      (not item.item.item.enabled is defined)
#    - item.item.ssl is defined
#    - item.item.ssl == 'acme'
#  with_items: '{{ getcert_sites }}'

