---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :
# tasks file for ip.webvhost

- include: dns.yml

- include: unix.yml
  when: ansible_os_family == 'Debian' or
        ansible_os_family == 'RedHat' or
        ansible_os_family == 'FreeBSD' or
        ansible_os_family == 'Kali GNU/Linux'

