---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :

# This task set is the same during both passes. Differences (do_ssl checks)
# are only present in the templates.

- name: Upload nginx config
  template:
    src: 'templates/nginx.conf.j2'
    dest: '{{ webvhost_nginx_config_dir }}/nginx.conf'
    backup: True
  register: vhost_upload

- name: Enable nginx (FreeBSD)
  lineinfile:
    path: /etc/rc.conf
    regexp: '^nginx_enable=".*"'
    line: 'nginx_enable="YES"'
  register: rc_enabled
  when: ansible_os_family == 'FreeBSD'

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  when: vhost_upload.changed or rc_enabled.changed

