---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :

- name: Upload nginx config
  template:
    src: 'templates/nginx.conf.j2'
    dest: '{{ webvhost_nginx_config_dir }}/nginx.conf'
    backup: True
  register: vhost_upload

- name: Restart nginx
  service:
    name: nginx2
    state: restarted
  when: vhost_upload.changed

