---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :

- name: Fetch SSL certificate inventory (FreeNAS)
  uri:
    url: '{{ webvhost_freenas_api_url }}/api/v1.0/system/certificate'
    method: GET
    user: '{{ webvhost_freenas_api_user }}'
    password: '{{ webvhost_freenas_api_password }}'
    body_format: json
    force_basic_auth: yes
    validate_certs: False
  delegate_to: localhost
  register: ssl_inventory
  no_log: true

- name: Upload existing SSL certificate (FreeNAS)
  copy:
    dest: '{{ webvhost_ssl_path }}/{{ item.0.server_name | default(inventory_hostname) }}.crt'
    content: >
      {{ item.1.cert_certificate }}{{ webvhost_freenas_ca }}
  when: 
  - (not item.0.server_name is defined and 
    inventory_hostname == item.1.cert_common) or
    (item.0.server_name is defined and
    item.0.server_name == item.1.cert_common)
  with_nested:
  - '{{ webvhost_sites }}'
  - '{{ ssl_inventory.json }}'

- name: Upload existing SSL private key (FreeNAS)
  copy:
    dest: '{{ webvhost_ssl_path }}/{{ item.0.server_name | default(inventory_hostname) }}.key'
    content: >
      {{ item.1.cert_privatekey }}
  when: 
  - (not item.0.server_name is defined and 
    inventory_hostname == item.1.cert_common) or
    (item.0.server_name is defined and
    item.0.server_name == item.1.cert_common)
  with_nested:
  - '{{ webvhost_sites }}'
  - '{{ ssl_inventory.json }}'

