---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :

#- name: Install OpenSSH
#  pkgng:
#    name: openssh
#    jail: '{{ item }}'
#  with_items: '{{ groups[jailsetup_jails_group] }}'

#- name: Check if jail is running
#  command: '{{ jailsetup_cmd_warden }} list | /usr/bin/grep ^{{ hostvars[jail].jail_name }}.\*Running'
#  register: jail_stats
#  with_items: '{{ groups[jailsetup_jails_group] }}'
#  loop_control:
#    loop_var: jail
#
#- name: Start jail
#  command: '{{ jailsetup_cmd_warden }} start {{ hostvars[jail].jail_name }}'
#  with_items: jail_stats.results
#  when: result.rc != 0
#  loop_control:
#    loop_var: result

- include_tasks:
    file: 'jail-net.yml'
  vars:
    jail_name: "{{ jail_inv.split('.')[0] }}"
  loop_control:
    loop_var: jail_inv
  when:
    - jail_interfaces is defined
    - jail_interfaces[jail_inv.split('.')[0]] is defined
  with_items: '{{ groups[jailsetup_jails_group] }}'

- include_tasks:
    file: 'jail-sshkey.yml'
  vars:
    jail_name: "{{ jail_inv.split('.')[0] }}"
  loop_control:
    loop_var: jail_inv
  with_items: '{{ groups[jailsetup_jails_group] }}'

- name: Set FreeBSD 11 Release
  lineinfile:
    regexp: 'url: "pkg\+http://pkg\.FreeBSD\.org/freebsd:11:x86:64/.*"'
    line: '  url: "pkg+http://pkg.FreeBSD.org/freebsd:11:x86:64/release_1",'
    path: "{{ jailsetup_jails_root }}/{{ jail_inv.split('.')[0] }}/usr/local/etc/pkg/repos/FreeBSD.conf"
  with_items: '{{ groups[jailsetup_jails_group] }}'
  loop_control:
    loop_var: jail_inv

# TODO: Remove unneccesary packages.

