---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :

- name: Enable VIMAGE on jail
  copy:
    content: ''
    dest: '{{ jailsetup_jails_root }}/.{{ jail_name }}.meta/vnet'

- name: Setup jail DNS
  copy:
    content: "nameserver {{ jail_interfaces[jail_name].dns }}\n"
    dest: '{{ jailsetup_jails_root }}/{{ jail_name }}/etc/resolv.conf'

- name: Setup alternative network interfaces ({{ jail_name }})
  copy:
    content: "{{ jail_interfaces[jail_name][item] }}\n"
    dest: '{{ jailsetup_jails_root }}/.{{ jail_name }}.meta/vn_{{ item }}'
  with_items: ['epair', 'gw', 'ip', 'netmask']
  when: jail_interfaces[jail_name][item] is defined

- name: Set system default gateways ({{ jail_name }})
  copy:
    content: "{{ jail_interfaces[jail_name].gw }}\n"
    dest: '{{ jailsetup_jails_root }}/.{{ jail_name }}.meta/defaultrouter-ipv4'
  when: jail_interfaces[jail_name].gw is defined

- name: Set internal jail hostnames ({{ jail_name }})
  copy:
    content: "{{ jail_name }}\n"
    dest: '{{ jailsetup_jails_root }}/.{{ jail_name }}.meta/host'

- name: Enable alternative network interface pre-start ({{ jail_name }})
  lineinfile:
    line: '{{ jailsetup_vn_script }} $JAILNAME {{ jail_interfaces[jail_name].zone }} prestart'
    dest: '{{ jailsetup_jails_root }}/.{{ jail_name }}.meta/jail-pre-start'

- name: Enable alternative network interface post-start ({{ jail_name }})
  lineinfile:
    line: '{{ jailsetup_vn_script }} $JAILNAME {{ jail_interfaces[jail_name].zone }} poststart'
    dest: '{{ jailsetup_jails_root }}/.{{ jail_name }}.meta/jail-post-start'

- name: Enable alternative network interface pre-stop ({{ jail_name }})
  lineinfile:
    line: '{{ jailsetup_vn_script }} $JAILNAME {{ jail_interfaces[jail_name].zone }} stop'
    dest: '{{ jailsetup_jails_root }}/.{{ jail_name }}.meta/jail-pre-stop'

