---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :

getcert_le_home: '/var/lib/letsencrypt'
getcert_certbot_pkg: certbot
getcert_ssl_path: '/etc/ssl'
getcert_le_dirs:
  work: '{{ getcert_le_home }}/work'
  config: '/etc/letsencrypt'
  logs: '{{ getcert_le_home }}/logs'

