---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :
# tasks file for ip.alerts

- include: nscp.yml
  when:
  - alerts_engine == 'nagios'
  - ansible_os_family == 'Windows'

- include: nrpe.yml
  when:
  - alerts_engine == 'nagios'
  - ansible_os_family == 'Debian' or 
    ansible_os_family == 'RedHat' or
    ansible_os_family == 'Kali GNU/Linux'

- include_tasks: check_mk.yml
  when:
  - alerts_engine == 'check_mk'

