---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :
# tasks file for ip.alerts

- include: nscp.yml
  when: ansible_os_family == 'Windows'

- include: nrpe.yml
  when: ansible_os_family == 'Debian' or 
        ansible_os_family == 'RedHat' or
        ansible_os_family == 'Kali GNU/Linux'

