---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :

- name: Install NSCP
  win_package:
    creates_service: nscp
    state: present
    path: '{{ alerts_nscp_installer }}'
    product_id: '{{ alerts_nscp_product_id }}'
    validate_certs: true
    arguments: CONF_CAN_CHANGE=1 ALLOWED_HOSTS={{ alerts_host }} CONF_NSCLIENT=1 CONF_NRPE=1 NRPEMODE=LEGACY
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only

- name: Upload NSCP config file
  win_template:
    src: templates/nsclient.ini.j2
    dest: "{{ alerts_nscp_root }}\\nsclient.ini"
  register: nscp

- name: Upload NSCP scripts
  win_copy:
    src: "{{ alerts_scripts_root }}/{{ item }}"
    dest: "{{ alerts_nscp_root }}\\scripts\\{{ item }}"
  loop: "{{ alerts_scripts }}"
  when: alerts_scripts is defined

- name: Restart NSClient
  win_service:
    name: nscp
    state: restarted
  when: nscp.changed

