---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :
# tasks file for ip.smb

- name: Upload configuration file
  template:
    src: templates/smb4.conf.j2
    dest: /usr/local/etc/smb4-new.conf  

