---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :
# tasks file for ip.smb

- include: linux-domain.yml
  when:
    - smb_security == 'ads'
    - ansible_os_family == 'Debian' or
      ansible_os_family == 'RedHat' or
      ansible_os_family == 'CentOS' or
      ansible_os_family == 'Kali GNU/Linux'

