---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :
# tasks file for ip.remotelog

- include: nxlog.yml
  when: ansible_os_family == 'Windows'

- include: rsyslog.yml
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

