---
# vim: set tabstop=2 expandtab shiftwidth=2 smarttab :

- name: Install rsyslog
  package:
    name: rsyslog
    state: present

- name: Upload rsyslog config
  template:
    src: templates/rsyslog.conf.j2
    dest: /etc/rsyslog.conf
  register: rlog

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted
  when: rlog.changed

